### PR TITLE
Atheurer sar

### PR DESCRIPTION
**Pull request by ndokos**
I think the sar branch needs rebasing: there are commits here that are already in master.

### CODE REVIEW

**Comment by atheurer** [comment]
Does it matter if there are same commits if github reports that it has no conflicts with the base branch?

**Comment by ndokos** [comment]
I don't know for sure, but my gut feeling is that it's safer to rebase first:  IIUC, after you rebase, then this PR should only show the sar-related commits.

**Comment by atheurer** [comment]
I have rebased, but required a push --force, which I always am uneasy about

**Comment by ndokos** [comment]
Have you pushed this to the DSA repo? I don't see the last commit and I don't see the travis CI kicking in.

**Comment by atheurer** [comment]
OK, I see I missed a step.  Your pull request has now been merged in to my branch, and that branch is a pull request for DSA, and the integration tests should now be running

**Comment by ndokos** [comment]
Great - thanks!

**Pull request merged**
