### PR TITLE
Unit test case for pcp.

### PR DESCRIPTION
**Pull request by ndokos**

### CODE REVIEW

**Comment by ndokos** [comment]
@atheurer: I can't make the pcp test pass consistently - failures seem to depend on pcp version: F22 runs 3.11 (no errors), RHEL7.2 runs 3.10 (failures with empty csv files), Ubuntu 12.04 runs 3.5 and there are more failures. I suggest you rip out the samples/pcp-0 and gold/pcp-0 directories and submit without unit tests. Apologies for the run-around.

**Comment by atheurer** [comment]
Agreed.  I think we have no other choice when we are dealing with a tool which we do not package ourselves, and can not strictly control the output.  For tools like this, having a unit test for post-processing is not feasible.

**Comment by ndokos** [comment]
Peter has some ideas about a test (on a vastly reduced scale) - I'll see what I can do in the next round.

There is also the question of the HTML files and what happens if/when Karl's changes go in.

**Comment by atheurer** [comment]
That's a good point about the csv files.  I wonder if we should have GenData only handle csv creation (for the tools that need it), and have another script work off only csv files in a directory to generate html.  That way it does not matter how the csv files are generated, in producing the html.

We talked about producing the html via client-side as a user browses the folder, but I suppose we could do this server side for the first attempt.  This could be either in pbench post-processing, or http server side as graphing directories are requested from the browser.

**Pull request merged**
