### PR TITLE
Run benchmark pp only.karl

### PR DESCRIPTION
**Pull request by k-rister**

### CODE REVIEW

**Comment by k-rister** [comment]
There might be a problem here so don't merge yet.

**Comment by k-rister** [comment]
Yeah, there is a bug that is going to take me awhile to resolve...more like a disease :(

**Comment by atheurer** [comment]
There are some changes I am making that should make creating metrics significantly easier, so it might be best to wait a couple days to see that code from me.  It should make your postprocessing metric gen a lot easier.

**Comment by k-rister** [comment]
Ok, eager to see it.  What I'm finding is that I 1) didn't completely remember the code I wrote months ago and 2) mistakenly assumed that the code written months ago was actually finished and working properly.

**Comment by k-rister** [comment]
So I still want to wait and look at your new methodology but I think this is working now.  Hopefully this provides a good base to adopt your changes since it is actually properly working now.

**Pull request closed without merging**
